config/routes.rb
Ginkgo::Application.routes.draw do
  resources :books

  resources :contacts

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :artworks

  get 'admin' => 'artworks#admin'

  resources :collections

  resources :materials

  resources :order_infos

  resources :illustrations

  get "faq/show"
  get "about_me/show"
  resources :news

  root 'welcomes#index'

  resources :welcomes

  resources :statuses

  resources :techniques

  get 'index' => 'artworks#gallery_index'

  get 'about_me' => 'about_me#show'

  get 'faq' => 'faq#show'

 

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :Collection
  belongs_to :Technique
  belongs_to :Material

  mount_uploader :image, ImageUploader
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :Artworks
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base

end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :Artworks
end

app/models/news.rb
class News < ActiveRecord::Base

	mount_uploader :image, ImageUploader
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
end

app/models/technique.rb
class Technique < ActiveRecord::Base
	has_many :Artworks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
	
  def show
  end
end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController
  before_action :set_illustration, only: [:show, :edit, :update, :destroy]
 
  # GET /illustrations
  # GET /illustrations.json
  def index
    @illustrations = Illustration.all
  end

  # GET /illustrations/1
  # GET /illustrations/1.json
  def show
  end

  # GET /illustrations/new
  def new
    @illustration = Illustration.new
  end

  # GET /illustrations/1/edit
  def edit
  end

  # POST /illustrations
  # POST /illustrations.json
  def create
    @illustration = Illustration.new(illustration_params)

    respond_to do |format|
      if @illustration.save
        format.html { redirect_to @illustration, notice: 'Illustration was successfully created.' }
        format.json { render action: 'show', status: :created, location: @illustration }
      else
        format.html { render action: 'new' }
        format.json { render json: @illustration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /illustrations/1
  # PATCH/PUT /illustrations/1.json
  def update
    respond_to do |format|
      if @illustration.update(illustration_params)
        format.html { redirect_to @illustration, notice: 'Illustration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @illustration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /illustrations/1
  # DELETE /illustrations/1.json
  def destroy
    @illustration.destroy
    respond_to do |format|
      format.html { redirect_to illustrations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_illustration
      @illustration = Illustration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def illustration_params
      params.require(:illustration).permit(:name, :image)
    end
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/illustrations_helper.rb
module IllustrationsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/helpers/wuffi_helper.rb
module WuffiHelper
end

app/views/illustrations/_form.html.erb
<%= simple_form_for(@illustration) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>

app/views/illustrations/edit.html.erb
<h1>Editing illustration</h1>

<%= render 'form' %>

<%= link_to 'Show', @illustration %> |
<%= link_to 'Back', illustrations_path %>

app/views/illustrations/index.html.erb
<h1>Illustrationer</h1>

<p>
  Behöver du hjälp med illustrationer? Kanske till till ett reklamblad, ditt företag eller en bok. Kontakta i så fall mig!
</p>
<p>
  Jag arbetar själv sedan en tid med en barnbok. Boken är inte färdig än, men jag kan bjuda på några smakprov på bilderna.
</p>
<p>
  <tbody>
    <% @illustrations.each do |illustration| %>
      <tr>
        <td>illustration</td>
        <td><%= link_to 'Ta bort', illustration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>
<br>
<%= link_to 'Lägg till', new_illustration_path %>

app/views/illustrations/new.html.erb
<h1>New illustration</h1>

<%= render 'form' %>

<%= link_to 'Back', illustrations_path %>

app/views/illustrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @illustration.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @illustration.image %>
</p>

<%= link_to 'Edit', edit_illustration_path(@illustration) %> |
<%= link_to 'Back', illustrations_path %>