config/routes.rb
Ginkgo::Application.routes.draw do
  resources :books

  resources :contacts

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :artworks

  get 'admin' => 'artworks#admin'

  resources :collections

  resources :materials

  resources :order_infos

  resources :illustrations

  get "faq/show"
  get "about_me/show"
  resources :news

  root 'welcomes#index'

  resources :welcomes

  resources :statuses

  resources :techniques

  get 'index' => 'artworks#gallery_index'

  get 'about_me' => 'about_me#show'

  get 'faq' => 'faq#show'

 

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :Collection
  belongs_to :Technique
  belongs_to :Material

  mount_uploader :image, ImageUploader
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :Artworks
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base

end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :Artworks
end

app/models/news.rb
class News < ActiveRecord::Base

	mount_uploader :image, ImageUploader
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
end

app/models/technique.rb
class Technique < ActiveRecord::Base
	has_many :Artworks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/helpers/wuffi_helper.rb
module WuffiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helena Fogelberg</title>
  <link href='http://fonts.googleapis.com/css?family=Crafty+Girls' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="fb-root"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/sv_SE/sdk.js#xfbml=1&appId=250032655171030&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  <div class='text-center title'>
    <h1>Helena Fogelberg</h1>
    <h3>Art and Design</h3>
    <br />
  </div>
	<%= render 'partials/menu' %>
    <div id="main-container" class="container">
      <div class="row">
        <div id="sidebar" class="col-xs-1">
          <!-- sidebar content -->
        </div>
        <div id="content" class="col-xs-11" class="col-center">
          <%= yield %>
        </div>
      </div>
    </div>
  <%= render 'partials/footer' %>
</body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56116001-1', 'auto');
  ga('send', 'pageview');

</script>

</html>

app/views/layouts/welcome_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helena Fogelberg</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br>
  <br>
  <br>
    <div id="main-container" class="container">
      <div class="row">
        <div id="sidebar" class="col-xs-1"></div>
        <div id="content" class="col-xs-10" class="col-center">
          <%= yield %>
        </div>
      </div>
      <div id="sidebar" class="col-xs-1"></div>
    </div>
</body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56116001-1', 'auto');
  ga('send', 'pageview');

</script>

</html>

app/views/partials/_footer.html.erb
<hr></hr>
<div class='footer'>
	&copy; Helena Fogelberg Art and Design
	<br />
	<span class='right'>
		<% if user_signed_in? %>
	  	Inloggad som <%= current_user.email %>.
	  	<%= link_to 'Ändra inloggning', edit_user_registration_path, :class => 'navbar-link' %> |
	  	<%= link_to "Logga ut", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% end %>
	</span>
	<br />
	<br /> 
</div>

app/views/partials/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">

      <li><%= link_to 'Hem ', artworks_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Samlingar<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% @collections.each do |collection| %>
            <li><%= link_to collection.name, artworks_path(:collectionId => collection.id) %></li>
          <% end %>
        </ul>
      </li>
      <% if user_signed_in? %> 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administrera<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li role='presentation'><%= link_to 'Konstverk', admin_path %></li>
            	<li role='presentations'><%= link_to 'Samlingar', collections_path %></li>
            	<li role='presentations'><%= link_to 'Tekniker', techniques_path %></li>
              <li role='presentations'><%= link_to 'Material', materials_path %></li>
            </ul>
          </li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Om<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li role='presentationa'><%= link_to 'Om mig', about_me_path %></li>
            <li role='presentations'><%= link_to 'Vanliga frågor', faq_path %></li>
          </ul>
      </li>
      <li><%= link_to 'Böcker', books_path %></li>
      <li><%= link_to 'Beställningar', order_infos_path %></li>
      <li><%= link_to 'Nyheter', news_index_path %></li>
      <li><%= link_to 'Kontakta mig!', contacts_path %></li>
    </ul>
</nav>