config/routes.rb
Ginkgo::Application.routes.draw do
  resources :books

  resources :contacts

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :artworks

  get 'admin' => 'artworks#admin'

  resources :collections

  resources :materials

  resources :order_infos

  resources :illustrations

  get "faq/show"
  get "about_me/show"
  resources :news

  root 'welcomes#index'

  resources :welcomes

  resources :statuses

  resources :techniques

  get 'index' => 'artworks#gallery_index'

  get 'about_me' => 'about_me#show'

  get 'faq' => 'faq#show'

 

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :Collection
  belongs_to :Technique
  belongs_to :Material

  mount_uploader :image, ImageUploader
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :Artworks
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base

end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :Artworks
end

app/models/news.rb
class News < ActiveRecord::Base

	mount_uploader :image, ImageUploader
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
end

app/models/technique.rb
class Technique < ActiveRecord::Base
	has_many :Artworks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
	
  def show
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
 
  # GET /news
  # GET /news.json
  def index
    #@news = News.all.order('id desc')

   @news = News.all.order('id desc').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:header, :body, :image)
    end
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/helpers/wuffi_helper.rb
module WuffiHelper
end

app/views/news/_form.html.erb
<% unless @news.image.blank?%><%= image_tag @news.image_url.to_s %><% end %>
<%= simple_form_for(@news) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :header, :label=>'Rubrik' %>
    <%= f.input :body, as: :text, :label=>'Text', :input_html => {:rows=>10, :columns=>10} %>
    <%= f.file_field :image, :label=>'Bild' %>
  </div>

   <div class="form-actions">
    <%= button_to 'Avbryt', news_index_path, :class=>'btn' %>
    <%= f.submit 'Spara', :class=>'btn btn-primary' %>	
  </div>
<% end %>

<% # jquery upload template # %>
<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>

app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<table>
  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td>
            <%= image_tag news.image.thumb.to_s, :class=>'preview' %>
        </td>
        <td>
          <h2><%= link_to news.header, news_path(news) %></h2>
          <p>
            <%= truncate(news.body) %>
          </p>
          <p>
            <div class='text-muted'><%= news.created_at.to_date %></div>
          </p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
  <div class='pagination'>
    <%= will_paginate @forum_posts, :container => false %>
  </div>
<br />


<% if user_signed_in? %>
  <%= link_to 'Lägg till', new_news_path %>
<% end %>

app/views/news/new.html.erb
<h1>Ny nyhet</h1>

<%= render 'form' %>

app/views/news/show.html.erb
<h2><%= @news.header %></h2>

<p>
	<%= image_tag @news.image.to_s %>
</p>
<p>
	<%= safe_join(@news.body.split("\r\n"), "<br />".html_safe) %>
</p>
<p>
	<div class='text-muted'><%= @news.created_at.to_date %></div>
</p>
<p>
	<%= link_to 'Åter till nyheter', news_index_path %>
</p>

<% if user_signed_in? %>
<p>
  <%= link_to 'Ändra', edit_news_path(@news) %>
  <%= link_to 'Ta bort', @news, method: :delete, data: { confirm: 'Är du säker?' } %>
<p>
<% end %>