config/routes.rb
Ginkgo::Application.routes.draw do
  resources :books

  resources :contacts

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :artworks

  get 'admin' => 'artworks#admin'

  resources :collections

  resources :materials

  resources :order_infos

  resources :illustrations

  get "faq/show"
  get "about_me/show"
  resources :news

  root 'welcomes#index'

  resources :welcomes

  resources :statuses

  resources :techniques

  get 'index' => 'artworks#gallery_index'

  get 'about_me' => 'about_me#show'

  get 'faq' => 'faq#show'

 

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :Collection
  belongs_to :Technique
  belongs_to :Material

  mount_uploader :image, ImageUploader
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :Artworks
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/illustration.rb
class Illustration < ActiveRecord::Base

end

app/models/material.rb
class Material < ActiveRecord::Base
	has_many :Artworks
end

app/models/news.rb
class News < ActiveRecord::Base

	mount_uploader :image, ImageUploader
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
end

app/models/technique.rb
class Technique < ActiveRecord::Base
	has_many :Artworks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
	
  def show
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	layout 'welcome_layout'
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]
	
  # GET /welcomes
  # GET /welcomes.json
  def index
    @artworks = Artwork.where(:for_sale=>true, :show=>true).order("RANDOM()").limit(5)
  end
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/helpers/wuffi_helper.rb
module WuffiHelper
end

app/views/welcomes/index.html.erb
<div class="jumbotron">
	<br>
  <div class="text-centre title">
    <h1>Helena Fogelberg</h1>
  	<h3>Art and Design</h3>
  </div>
	<br>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <% for i in 1..@artworks.count %>
        <li data-target="#carousel-example-generic" data-slide-to="#{i}"></li>
      <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active carouselItem">
        <%= link_to (image_tag @artworks.last.image.medium.to_s), artwork_path(@artworks.last) unless @artworks.last.image.blank? %>
      </div>
      	<% @artworks.each do |artwork| %>
      		<div class="item carouselItem">
      			<%= link_to (image_tag artwork.image.medium.to_s), artwork_path(artwork) unless artwork.image.blank? %>
      		</div>
    		<% end %>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>

    <br>
    <p>
      <%= link_to 'Välkommen!', artworks_path, :class=>'btn btn-primary btn-lg' %>
    </p>
  </div>
	<br>
</div>